### ISSUE TITLE
request: feature to not change address every time you spent

### ISSUE THREAD

**Issue by angryolk** [mochimodev/mojo-java-wallet#10]
Hi, is it possible to keep using the same address every time you spent MCM? maybe you can have an option in the wallet: 1. roll source address .  2. keep source address 
and make keep source address as default?

**Comment by 0rtis** [comment]
Mochimo is based on the quantum secured WOTS signature scheme. WOTS address should **never** be used more than once to remain secured. We recommend to only use Tagged address, since the Tag can be reused multiple time without impacting the security of the signature.
http://www.mochiwiki.com/w/index.php/TAG_explanation
