### ISSUE TITLE
request: automatic expand address pools when it is 0

### ISSUE THREAD

**Issue by angryolk** [mochimodev/mojo-java-wallet#15]
i believe this process can excutable automatically to simplifies user experience. if available address are lower than 10 for example, system then expand available address to 100 automatically.

**Comment by 0rtis** [comment]
Next version include an automatic expand after creation of the wallet. We cannot have an auto expand anytime the pool of address falls below a threshold because it is a time consuming process. We want to avoid a situation where a user need to urgently send a transaction, just to be met by a several minute auto expand.
